import BEMOCFormalization.Core
import BEMOCFormalization.ConcreteWithinRing
import BEMOCFormalization.CrossRingEstimate
import BEMOCFormalization.LatitudeAxialBridge
import BEMOCFormalization.LatitudeAngularExpansion
import BEMOCFormalization.LatitudeAngularJetBounds
import BEMOCFormalization.LatitudeBands
import BEMOCFormalization.LatitudeCentralGeometry
import BEMOCFormalization.LatitudeCentralOppositeBlocks
import BEMOCFormalization.LatitudeCoefficientDerivatives
import BEMOCFormalization.LatitudeComparableBlocks
import BEMOCFormalization.LatitudeComparableCuspJet
import BEMOCFormalization.LatitudeComparableGeometry
import BEMOCFormalization.LatitudeComparableGapGeometry
import BEMOCFormalization.LatitudeComparableRadiusBounds
import BEMOCFormalization.LatitudeComparableSeparatedClosure
import BEMOCFormalization.LatitudeComparableSharpJetClosure
import BEMOCFormalization.LatitudeComparableDerivativeEnvelope
import BEMOCFormalization.LatitudeDecomposition
import BEMOCFormalization.LatitudeDiagonalCuspBlocks
import BEMOCFormalization.LatitudeDiagonalBandBridge
import BEMOCFormalization.LatitudeEstimate
import BEMOCFormalization.LatitudeExceptionalGeometry
import BEMOCFormalization.LatitudeExceptionalSeriesClosure
import BEMOCFormalization.LatitudeFiniteFallback
import BEMOCFormalization.LatitudeConcreteBlocks
import BEMOCFormalization.LatitudeKernelLocal
import BEMOCFormalization.LatitudeL2
import BEMOCFormalization.LatitudeMixedTaylorSpecialization
import BEMOCFormalization.LatitudeNeighboringRegularBlocks
import BEMOCFormalization.LatitudePairClassification
import BEMOCFormalization.LatitudePairSymmetry
import BEMOCFormalization.LatitudeOppositeGeometry
import BEMOCFormalization.LatitudePointwiseAssembly
import BEMOCFormalization.LatitudePolarBlocks
import BEMOCFormalization.LatitudePowerJetBounds
import BEMOCFormalization.LatitudeRowArithmetic
import BEMOCFormalization.LatitudeSmoothOppositeBlocks
import BEMOCFormalization.LatitudePushforward
import BEMOCFormalization.LatitudeSeparatedBlocks
import BEMOCFormalization.LatitudeUnequalBlocks
import BEMOCFormalization.LatitudeUnequalGeometry
import BEMOCFormalization.LatitudeUnequalPeanoBridge
import BEMOCFormalization.LatitudeUnequalSeries
import BEMOCFormalization.LatitudeUnequalSummand
import BEMOCFormalization.LatitudeUnequalSeriesClosure
import BEMOCFormalization.LatitudeVariableMixedBound
import BEMOCFormalization.LatitudeVariableMixedDerivative
import BEMOCFormalization.LatitudeWeakSingularity
import BEMOCFormalization.ReducedCuspDerivatives
import BEMOCFormalization.ReducedCuspLocalDecomposition
import BEMOCFormalization.ReducedCuspResonant
import BEMOCFormalization.ReducedCuspQuadratic
import BEMOCFormalization.RealBinomialSeries
import BEMOCFormalization.MixedTaylorRemainder
import BEMOCFormalization.MainTheorem
import BEMOCFormalization.TwoMomentPeano
import BEMOCFormalization.WithinRingLimit

/-!
# BEMOC negative Riesz energies

Public entry point for the core formalization, the concrete within-ring
and cross-ring estimates, and the sharp square-subsequence within-ring limit.
-/
