#!/usr/bin/env python3
"""Inline this project's transitive Lean modules into one Mathlib-only source file.

This is a source transformation, not a proof. Lean must elaborate the output.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
IMPORT = re.compile(r"^import\s+(.+?)\s*$")
LOCAL_PREFIX = "BEMOCFormalization."
PRIVATE_DECL = re.compile(
    r"^\s*private\s+(?:(?:noncomputable|unsafe|partial)\s+)*"
    r"(?:theorem|lemma|def|abbrev)\s+([A-Za-z_][A-Za-z0-9_']*)\b",
    re.MULTILINE,
)


def source_for(module: str) -> Path:
    path = ROOT / (module.replace(".", "/") + ".lean")
    if not path.is_file():
        raise FileNotFoundError(f"missing local module {module}: {path}")
    return path


def order_modules(entry: str) -> tuple[list[str], list[str]]:
    ordered: list[str] = []
    external: list[str] = []
    visited: set[str] = set()
    active: set[str] = set()

    def visit(module: str) -> None:
        if module in visited:
            return
        if module in active:
            raise ValueError(f"import cycle at {module}")
        active.add(module)
        for line in source_for(module).read_text().splitlines():
            match = IMPORT.fullmatch(line)
            if match is None:
                continue
            for dependency in match.group(1).split():
                if dependency.startswith(LOCAL_PREFIX):
                    visit(dependency)
                elif dependency not in external:
                    external.append(dependency)
        active.remove(module)
        visited.add(module)
        ordered.append(module)

    visit(entry)
    return ordered, external


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--entry", default="BEMOCFormalization")
    parser.add_argument("--output", type=Path, default=ROOT / "comparator/SelfContained.lean")
    args = parser.parse_args()
    ordered, external = order_modules(args.entry)
    chunks = ["/- Generated by scripts/export_self_contained.py. Verify with Lean. -/\n"]
    chunks.extend(f"import {module}\n" for module in external)
    for module in ordered:
        source = source_for(module).read_text()
        body = "\n".join(line for line in source.splitlines() if not IMPORT.fullmatch(line))
        # `private` names are scoped to a source file in Lean. A single merged
        # file loses that boundary, so qualify each private name by its module.
        for name in sorted(set(PRIVATE_DECL.findall(body)), key=len, reverse=True):
            qualified = f"{module.rsplit('.', 1)[-1]}_{name}"
            body = re.sub(rf"(?<![\w.]){re.escape(name)}\b", qualified, body)
        # File-level `open`, `open scoped`, variables, and options must not leak
        # into the following inlined module.
        # Auxiliary-lemma cache is `.local` to a Lean module and is not saved
        # to oleans. Reset it here so generated proof constants have the same
        # names as in the separately compiled challenge modules.
        chunks.append(
            "\nrun_cmd Lean.modifyEnv fun env => "
            "Lean.Meta.auxLemmasExt.modifyState env fun _ => {}\n"
            f"/- Begin {module} -/\nsection\n{body.rstrip()}\nend\n"
            f"/- End {module} -/\n"
        )
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    # Keep the emitted source free of trailing whitespace even if a source
    # module is being cleaned up concurrently.
    output.write_text("\n".join(line.rstrip() for line in "".join(chunks).split("\n")))
    print(f"Wrote {output} from {len(ordered)} project modules; external imports: {external}")


if __name__ == "__main__":
    main()
