/- Generated by scripts/export_self_contained.py. Verify with Lean. -/
import Mathlib

/- Begin BEMOCFormalization.Core -/

/-! Basic geometric objects. Targets in later modules are propositions, not proofs. -/
open scoped BigOperators
open MeasureTheory
namespace BEMOC
namespace Definitive

/-- Euclidean ambient space; chordal distance is inherited from this space. -/
abbrev Ambient := EuclideanSpace ℝ (Fin 3)
/-- The unit sphere. -/
abbrev Sphere := Metric.sphere (0 : Ambient) 1

/-- Latitude parametrization, before enforcing the height domain. -/
noncomputable def parallelVector (z θ : ℝ) : Ambient :=
  !₂[Real.sqrt (1 - z ^ 2) * Real.cos θ,
     Real.sqrt (1 - z ^ 2) * Real.sin θ, z]

/-- Reused geometric argument from the previous Core, independent of its construction. -/
theorem parallelVector_mem_sphere {z θ : ℝ} (hz : z ∈ Set.Icc (-1 : ℝ) 1) :
    parallelVector z θ ∈ Metric.sphere (0 : Ambient) 1 := by
  rw [EuclideanSpace.sphere_zero_eq 1 (by positivity)]
  have hrad : 0 ≤ 1 - z ^ 2 := by nlinarith [hz.1, hz.2]
  simp [parallelVector, Fin.sum_univ_succ, Real.sq_sqrt hrad]
  ring_nf
  rw [Real.sq_sqrt hrad]
  nlinarith [Real.sin_sq_add_cos_sq θ]

/-- The exact point on a parallel, with its height condition explicit. -/
noncomputable def parallelPoint (z θ : ℝ) (hz : z ∈ Set.Icc (-1 : ℝ) 1) : Sphere :=
  ⟨parallelVector z θ, parallelVector_mem_sphere hz⟩

/-- Normalized geometric surface measure, using mathlib's polar measure. -/
noncomputable def sigma : Measure Sphere :=
  (volume.toSphere (E := Ambient) Set.univ)⁻¹ • volume.toSphere

/-- The manuscript's continuous energy constant. -/
noncomputable def continuousEnergy (α : ℝ) : ℝ := 2 ^ (α + 1) / (α + 2)

/-- Ordered-pair energy including the diagonal, which vanishes for `0 < α`. -/
noncomputable def energy {ι : Type*} [Fintype ι] (X : ι → Sphere) (α : ℝ) : ℝ :=
  ∑ i, ∑ j, dist (X i) (X j) ^ α

/-- The target second-order scale. -/
noncomputable def scale (α : ℝ) (N : ℕ) : ℝ := (N : ℝ) ^ (1 - α / 2)

/-- Average kernel for two uniform parallels; meaningful on `[-1,1]²`. -/
noncomputable def latitudeKernel (α s t : ℝ) : ℝ :=
  (2 * Real.pi)⁻¹ * ∫ θ in (0 : ℝ)..2 * Real.pi,
    (2 - 2 * s * t - 2 * Real.sqrt (1 - s ^ 2) *
      Real.sqrt (1 - t ^ 2) * Real.cos θ) ^ (α / 2)

/-- Algebraic specialization used by the discrepancy corollary. -/
theorem continuousEnergy_one : continuousEnergy 1 = 4 / 3 := by
  norm_num [continuousEnergy]

end Definitive
end BEMOC
/- End BEMOCFormalization.Core -/

/- Begin BEMOCFormalization.Construction -/

open scoped BigOperators
namespace BEMOC.Definitive

/-- Integer version of `floor(sqrt(N/4))`; division here is natural-number division. -/
def bandParameter (N : ℕ) : ℕ := Nat.sqrt (N / 4)
/-- Population of a one-based band. Only indices `1,...,2M-1` are occupied. -/
def population (N j : ℕ) : ℕ :=
  let M := bandParameter N
  if j < M then 4 * j
  else if j = M then N - 4 * M * (M - 1)
  else 4 * (2 * M - j)
/-- Boundary heights, defined from cumulative populations, including `H₀=1`. -/
noncomputable def boundary (N j : ℕ) : ℝ :=
  1 - 2 / (N : ℝ) * ∑ k ∈ Finset.Icc 1 j, (population N k : ℝ)
/-- Midpoint height, defined from the boundaries. -/
noncomputable def height (N j : ℕ) : ℝ := (boundary N (j - 1) + boundary N j) / 2
/-- Radius of an occupied parallel. -/
noncomputable def radius (N j : ℕ) : ℝ := Real.sqrt (1 - height N j ^ 2)
/-- Closed height band; endpoints have zero Lebesgue mass. -/
def band (N j : ℕ) : Set ℝ := Set.Icc (boundary N j) (boundary N (j - 1))
/-- Zero-based finite band labels; add one to recover the manuscript index. -/
abbrev RingIndex (N : ℕ) := Fin (2 * bandParameter N - 1)
/-- Every polygon vertex has its own label. -/
abbrev PointIndex (N : ℕ) := Σ j : RingIndex N, Fin (population N (j.val + 1))
/-- Independent azimuthal phases on the occupied parallels. -/
abbrev Phases (N : ℕ) := RingIndex N → ℝ

/-- Total definition. The north-pole fallback is unreachable after proving `ConstructionFacts`. -/
noncomputable def point (N : ℕ) (φ : Phases N) (i : PointIndex N) : Sphere :=
  let j := i.1.val + 1
  if h : height N j ∈ Set.Icc (-1 : ℝ) 1 then
    parallelPoint (height N j)
      (φ i.1 + 2 * Real.pi * (i.2.val : ℝ) / (population N j : ℝ)) h
  else parallelPoint 1 0 (by norm_num)

/-- The exact finite energy of the new Diamond points. -/
noncomputable def diamondEnergy (α : ℝ) (N : ℕ) (φ : Phases N) : ℝ :=
  energy (point N φ) α

/-- Construction obligations, including distinctness needed to speak about an N-element set. -/
def ConstructionFacts : Prop :=
  ∀ N : ℕ, 4 ≤ N →
    1 ≤ bandParameter N ∧
    4 * bandParameter N ^ 2 ≤ N ∧
    N < 4 * (bandParameter N + 1) ^ 2 ∧
    (∑ j : RingIndex N, population N (j.val + 1)) = N ∧
    (∀ j : RingIndex N, 0 < population N (j.val + 1) ∧
      height N (j.val + 1) ∈ Set.Ioo (-1 : ℝ) 1) ∧
    (∀ φ : Phases N, Function.Injective (point N φ))

/-- Closed formulas to prove from cumulative populations. -/
def BoundaryFormulas : Prop :=
  ∀ N : ℕ, 4 ≤ N →
    (∀ j : ℕ, j < bandParameter N →
      boundary N j = 1 - 4 * (j : ℝ) * (j + 1) / N) ∧
    (∀ j : ℕ, 1 ≤ j → j < bandParameter N →
      height N j = 1 - 4 * (j : ℝ) ^ 2 / N) ∧
    height N (bandParameter N) = 0 ∧
    (∀ j : ℕ, 1 ≤ j → j < 2 * bandParameter N →
      height N (2 * bandParameter N - j) = -height N j)

end BEMOC.Definitive
/- End BEMOCFormalization.Construction -/

/- Begin BEMOCFormalization.Geometry -/

open scoped BigOperators
namespace BEMOC.Definitive

/-- Uniform geometric estimates; constants never depend on N or phases. -/
def GeometryBounds : Prop :=
  ∃ c C : ℝ, 0 < c ∧ 0 < C ∧ ∀ N : ℕ, 4 ≤ N →
    (∀ j : RingIndex N,
      c * bandParameter N * radius N (j.val + 1) ≤ population N (j.val + 1) ∧
      (population N (j.val + 1) : ℝ) ≤
        C * bandParameter N * radius N (j.val + 1)) ∧
    (∀ j : RingIndex N, population N (j.val + 1) ≤ 15 * bandParameter N) ∧
    (∀ n : ℕ, (Finset.univ.filter
      (fun j : RingIndex N => population N (j.val + 1) = n)).card ≤ 3)

/-- Polar interval in increasing angular coordinates. -/
def polarBand (N j : ℕ) : Set ℝ :=
  Set.Icc (Real.arccos (boundary N (j - 1))) (Real.arccos (boundary N j))

/-- Polar geometry used for block estimates, after the explicit large-N cutoff. -/
def AngularGeometry : Prop :=
  ∃ c C : ℝ, 0 < c ∧ 0 < C ∧ ∀ N : ℕ, 16 ≤ bandParameter N →
    (∀ j : RingIndex N,
      c / bandParameter N ≤ Real.arccos (boundary N (j.val + 1)) -
        Real.arccos (boundary N j.val) ∧
      Real.arccos (boundary N (j.val + 1)) - Real.arccos (boundary N j.val)
        ≤ C / bandParameter N) ∧
    (∀ j : RingIndex N, j.val ≠ 0 → j.val + 1 ≠ 2 * bandParameter N - 1 →
      ∀ θ ∈ polarBand N (j.val + 1),
        c * population N (j.val + 1) / bandParameter N ≤ Real.sin θ ∧
        Real.sin θ ≤ C * population N (j.val + 1) / bandParameter N) ∧
    (∀ j k : RingIndex N, 2 ≤ |(j.val : ℤ) - k.val| →
      ∀ θ ∈ polarBand N (j.val + 1), ∀ ψ ∈ polarBand N (k.val + 1),
        c * |(j.val : ℝ) - k.val| / bandParameter N ≤ |θ - ψ| ∧
        |θ - ψ| ≤ C * |(j.val : ℝ) - k.val| / bandParameter N)

end BEMOC.Definitive
/- End BEMOCFormalization.Geometry -/

/- Begin BEMOCFormalization.ContinuousEnergy -/

open MeasureTheory
namespace BEMOC.Definitive

/-- Geometric normalized surface area has the height-angle integration formula. -/
def SurfaceIntegration : Prop :=
  IsProbabilityMeasure sigma ∧
  ∀ f : Ambient → ℝ, Continuous f →
    (∫ x : Sphere, f x ∂sigma) =
      (1 / 2 : ℝ) * ∫ t in (-1 : ℝ)..1,
        (2 * Real.pi)⁻¹ * ∫ θ in (0 : ℝ)..2 * Real.pi, f (parallelVector t θ)

/-- Rotational invariance and the beta integral give a constant potential. -/
def ConstantPotential (α : ℝ) : Prop :=
  ∀ x : Sphere, (∫ y : Sphere, dist x y ^ α ∂sigma) = continuousEnergy α

/-- Finite-configuration nonnegativity, for the actual geometric surface constant. -/
def EnergyNonnegative (α : ℝ) : Prop :=
  ∀ n : ℕ, ∀ X : Fin n → Sphere,
    0 ≤ continuousEnergy α * (n : ℝ) ^ 2 - energy X α

/-- Measure-level negative type, stated using differences of positive finite measures. -/
def MeasureNegativeType (α : ℝ) : Prop :=
  ∀ μ ν : Measure Sphere, IsFiniteMeasure μ → IsFiniteMeasure ν →
    μ Set.univ = ν Set.univ →
    (∫ x, ∫ y, dist x y ^ α ∂μ ∂μ) +
      (∫ x, ∫ y, dist x y ^ α ∂ν ∂ν) -
        2 * (∫ x, ∫ y, dist x y ^ α ∂ν ∂μ) ≤ 0

end BEMOC.Definitive
/- End BEMOCFormalization.ContinuousEnergy -/

/- Begin BEMOCFormalization.EnergyDecomposition -/

open scoped BigOperators
namespace BEMOC.Definitive

/-- Energy of the weighted union of uniform parallels. -/
noncomputable def ringEnergy (α : ℝ) (N : ℕ) : ℝ :=
  ∑ j : RingIndex N, ∑ k : RingIndex N,
    (population N (j.val + 1) : ℝ) * population N (k.val + 1) *
      latitudeKernel α (height N (j.val + 1)) (height N (k.val + 1))
/-- Latitude error A. -/
noncomputable def latitudeError (α : ℝ) (N : ℕ) : ℝ :=
  continuousEnergy α * (N : ℝ) ^ 2 - ringEnergy α N
/-- Angular discretization error B; phases are retained. -/
noncomputable def longitudeError (α : ℝ) (N : ℕ) (φ : Phases N) : ℝ :=
  ringEnergy α N - diamondEnergy α N φ
/-- The actual energy deficit appearing in Theorem 1. -/
noncomputable def deficit (α : ℝ) (N : ℕ) (φ : Phases N) : ℝ :=
  continuousEnergy α * (N : ℝ) ^ 2 - diamondEnergy α N φ

/-- The two-term decomposition is algebraic and already proved. -/
theorem deficit_eq_latitude_add_longitude (α : ℝ) (N : ℕ) (φ : Phases N) :
    deficit α N φ = latitudeError α N + longitudeError α N φ := by
  unfold deficit latitudeError longitudeError
  ring

/-- Required geometric identification, including the finite-label cardinality. -/
def DiamondNonnegative (α : ℝ) : Prop :=
  ∀ N : ℕ, 4 ≤ N → ∀ φ : Phases N, 0 ≤ deficit α N φ

end BEMOC.Definitive
/- End BEMOCFormalization.EnergyDecomposition -/

/- Begin BEMOCFormalization.BandErrors -/

open scoped BigOperators
namespace BEMOC.Definitive

/-- Integration against λ_j−ν_j, implemented as a difference of ordinary integrals. -/
noncomputable def bandError (N j : ℕ) (f : ℝ → ℝ) : ℝ :=
  (N : ℝ) / 2 * (∫ t in boundary N j..boundary N (j - 1), f t) -
    (population N j : ℝ) * f (height N j)

/-- Ordered tensor of the two band error functionals: j acts on s, k on t. -/
noncomputable def bandBlock (N j k : ℕ) (G : ℝ × ℝ → ℝ) : ℝ :=
  bandError N j (fun s => bandError N k (fun t => G (s, t)))
/-- The actual latitude kernel block. -/
noncomputable def kernelBlock (α : ℝ) (N j k : ℕ) : ℝ :=
  bandBlock N j k (fun p => latitudeKernel α p.1 p.2)

/-- Exact two-moment cancellation, derived from the midpoint and mass formulas. -/
def BandMoments : Prop :=
  ∀ N : ℕ, 4 ≤ N → ∀ j : RingIndex N,
    bandError N (j.val + 1) (fun _ => 1) = 0 ∧
    bandError N (j.val + 1) id = 0

/-- Corrected variable binding for eq:latitude-decomposition. -/
def LatitudeIdentity (α : ℝ) : Prop :=
  ∀ N : ℕ, 4 ≤ N → latitudeError α N =
    -∑ j : RingIndex N, ∑ k : RingIndex N, kernelBlock α N (j.val + 1) (k.val + 1)

/-- Exchange symmetry used when orienting unequal-scale ordered pairs. -/
def BlockSymmetry (α : ℝ) : Prop :=
  ∀ N : ℕ, 4 ≤ N → ∀ j k : RingIndex N,
    kernelBlock α N (j.val + 1) (k.val + 1) =
      kernelBlock α N (k.val + 1) (j.val + 1)

end BEMOC.Definitive
/- End BEMOCFormalization.BandErrors -/

/- Begin BEMOCFormalization.Taylor -/

namespace BEMOC.Definitive

/-- Two derivatives in each height variable, in a fixed order. -/
noncomputable def mixedFourth (G : ℝ × ℝ → ℝ) (s t : ℝ) : ℝ :=
  iteratedDeriv 2 (fun u => iteratedDeriv 2 (fun v => G (u, v)) t) s

/-- The two-moment estimate for a C⁴ extension around a closed rectangle. -/
def MixedTaylorBound : Prop :=
  ∀ N : ℕ, 4 ≤ N → ∀ j k : RingIndex N,
    ∀ G : ℝ × ℝ → ℝ, ∀ W : Set (ℝ × ℝ), IsOpen W →
      (band N (j.val + 1) ×ˢ band N (k.val + 1)) ⊆ W →
      ContDiffOn ℝ 4 G W → ∀ L : ℝ, 0 ≤ L →
      (∀ p ∈ band N (j.val + 1) ×ˢ band N (k.val + 1),
        |mixedFourth G p.1 p.2| ≤ L) →
      |bandBlock N (j.val + 1) (k.val + 1) G| ≤
        (population N (j.val + 1) : ℝ) ^ 3 *
          (population N (k.val + 1) : ℝ) ^ 3 / (bandParameter N : ℝ) ^ 8 * L

end BEMOC.Definitive
/- End BEMOCFormalization.Taylor -/

/- Begin BEMOCFormalization.KernelDerivatives -/

namespace BEMOC.Definitive

/-- Distance power in polar coordinates, used only away from zero distance for differentiation. -/
noncomputable def polarKernel (α θ φ ψ : ℝ) : ℝ :=
  (2 - 2 * (Real.cos φ * Real.cos ψ +
    Real.sin φ * Real.sin ψ * Real.cos θ)) ^ (α / 2)

/-- The angular derivative estimate from Lemma derivative-bounds. -/
def PolarDerivativeBound (α : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ m n : ℕ, m + n ≤ 4 → ∀ θ φ ψ : ℝ,
    0 < 2 - 2 * (Real.cos φ * Real.cos ψ +
      Real.sin φ * Real.sin ψ * Real.cos θ) →
    |iteratedDeriv m (fun u => iteratedDeriv n (fun v => polarKernel α θ u v) ψ) φ| ≤
      C * (2 - 2 * (Real.cos φ * Real.cos ψ +
        Real.sin φ * Real.sin ψ * Real.cos θ)) ^ ((α - m - n) / 2)

/-- Smooth extension of the separated averaged kernel, including polar boundaries. -/
def SeparatedDerivativeBound (α : ℝ) : Prop :=
  ∀ ε : ℝ, 0 < ε → ε < 1 → ∃ C : ℝ, 0 < C ∧
    ∀ s ∈ Set.Icc (-1 : ℝ) 1, ∀ t ∈ Set.Icc (-1 : ℝ) 1,
      0 < 2 - 2 * s * t →
      2 * Real.sqrt (1 - s ^ 2) * Real.sqrt (1 - t ^ 2) ≤
        (1 - ε) * (2 - 2 * s * t) →
      ∃ G : ℝ × ℝ → ℝ, ∃ W : Set (ℝ × ℝ), IsOpen W ∧ (s, t) ∈ W ∧
        ContDiffOn ℝ 4 G W ∧
        (∀ p ∈ W, p.1 ∈ Set.Icc (-1 : ℝ) 1 → p.2 ∈ Set.Icc (-1 : ℝ) 1 →
          G p = latitudeKernel α p.1 p.2) ∧
        |mixedFourth G s t| ≤ C * (2 - 2 * s * t) ^ (α / 2 - 4)

end BEMOC.Definitive
/- End BEMOCFormalization.KernelDerivatives -/

/- Begin BEMOCFormalization.ComparableBlocks -/

namespace BEMOC.Definitive

/-- Symmetric scale-comparability predicate, using real rather than truncated division. -/
def Comparable (N j k : ℕ) : Prop :=
  (population N j : ℝ) / 8 ≤ population N k ∧
    (population N k : ℝ) ≤ 8 * population N j

/-- The full comparable estimate, including equal, adjacent, polar, and opposite bands. -/
def ComparableBlockBound (α : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ N : ℕ, 1024 ≤ N → ∀ j k : RingIndex N,
    Comparable N (j.val + 1) (k.val + 1) →
    |kernelBlock α N (j.val + 1) (k.val + 1)| ≤
      C * population N (j.val + 1) / (bandParameter N : ℝ) ^ α *
        (1 + |(j.val : ℝ) - k.val|) ^ (α - 3)

end BEMOC.Definitive
/- End BEMOCFormalization.ComparableBlocks -/

/- Begin BEMOCFormalization.UnequalBlocks -/

namespace BEMOC.Definitive

/-- Strictly on the same side; the central index is excluded. -/
def SameSide (N j k : ℕ) : Prop :=
  (j < bandParameter N ∧ k < bandParameter N) ∨
    (bandParameter N < j ∧ bandParameter N < k)

/-- Unequal scales in one hemisphere, oriented with k the larger population. -/
def SameSideBlockBound (α : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ N : ℕ, 1024 ≤ N → ∀ j k : RingIndex N,
    8 * population N (j.val + 1) < population N (k.val + 1) →
    SameSide N (j.val + 1) (k.val + 1) →
    |kernelBlock α N (j.val + 1) (k.val + 1)| ≤
      C * (population N (j.val + 1) : ℝ) ^ 3 /
        ((bandParameter N : ℝ) ^ α * (population N (k.val + 1) : ℝ) ^ (5 - α))

/-- Unequal opposite/central blocks; the central band belongs in this regime. -/
def OppositeBlockBound (α : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ N : ℕ, 1024 ≤ N → ∀ j k : RingIndex N,
    8 * population N (j.val + 1) < population N (k.val + 1) →
    ¬SameSide N (j.val + 1) (k.val + 1) →
    |kernelBlock α N (j.val + 1) (k.val + 1)| ≤
      C * (population N (j.val + 1) : ℝ) ^ 3 *
        (population N (k.val + 1) : ℝ) ^ 3 / (bandParameter N : ℝ) ^ 8

end BEMOC.Definitive
/- End BEMOCFormalization.UnequalBlocks -/

/- Begin BEMOCFormalization.Latitude -/

namespace BEMOC.Definitive

/-- Latitude bound after summing the three block regimes. -/
def LatitudeBound (α : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ N : ℕ, 1024 ≤ N →
    |latitudeError α N| ≤ C * scale α N

/-- Uniform finite-size bound, also uniform over the continuously varying phases. -/
def SmallSizeBound (α : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ N : ℕ, 4 ≤ N → N < 1024 →
    ∀ φ : Phases N, deficit α N φ ≤ C * scale α N

end BEMOC.Definitive
/- End BEMOCFormalization.Latitude -/

/- Begin BEMOCFormalization.FourierDecay -/

namespace BEMOC.Definitive

/-- The even real profile used in Appendix 1, including the cusp at δ=0. -/
noncomputable def fourierProfile (a δ θ : ℝ) : ℝ := (1 + δ - Real.cos θ) ^ a
/-- Real cosine coefficient; the sine coefficient vanishes by evenness. -/
noncomputable def cosineCoefficient (f : ℝ → ℝ) (n : ℕ) : ℝ :=
  (2 * Real.pi)⁻¹ * ∫ θ in (0 : ℝ)..2 * Real.pi, f θ * Real.cos (n * θ)

/-- Appendix 1 monotonicity, including δ=0 and all positive frequencies. -/
def FourierDomination (a : ℝ) : Prop :=
  ∀ δ : ℝ, 0 ≤ δ → ∀ n : ℕ, 1 ≤ n →
    cosineCoefficient (fourierProfile a 0) n ≤ cosineCoefficient (fourierProfile a δ) n ∧
    cosineCoefficient (fourierProfile a δ) n ≤ 0

/-- Gamma formula for the cusp profile; positive n avoids the zero mode. -/
def CuspCoefficientFormula (a : ℝ) : Prop :=
  ∀ n : ℕ, 1 ≤ n →
    cosineCoefficient (fourierProfile a 0) n =
      -(2 : ℝ) ^ (-a) * Real.Gamma (2 * a + 1) * Real.sin (Real.pi * a) /
        Real.pi * (Real.Gamma (n - a) / Real.Gamma (n + a + 1))

/-- Uniform Fourier decay; the constant is outside all geometric parameters. -/
def FourierDecayBound (a : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ δ : ℝ, 0 ≤ δ → ∀ n : ℕ, 1 ≤ n →
    |cosineCoefficient (fourierProfile a δ) n| ≤ C * (n : ℝ) ^ (-1 - 2 * a)

end BEMOC.Definitive
/- End BEMOCFormalization.FourierDecay -/

/- Begin BEMOCFormalization.Trapezoid -/

open scoped BigOperators
namespace BEMOC.Definitive

/-- Phase-shifted equally spaced quadrature on a full angular period. -/
noncomputable def angularAverage (L : ℕ) (φ : ℝ) (f : ℝ → ℝ) : ℝ :=
  (L : ℝ)⁻¹ * ∑ k : Fin L, f (φ + 2 * Real.pi * (k.val : ℝ) / L)
/-- The angular distance-power model. -/
noncomputable def angularKernel (α A B θ : ℝ) : ℝ := (A - B * Real.cos θ) ^ (α / 2)

/-- Lemma trap, with B=0, A=B, L=1 and arbitrary phase all retained. -/
def TrapezoidBound (α : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ A B : ℝ, 0 ≤ B → B ≤ A →
    ∀ L : ℕ, 1 ≤ L → ∀ φ : ℝ,
      |angularAverage L φ (angularKernel α A B) -
        (2 * Real.pi)⁻¹ * ∫ θ in (0 : ℝ)..2 * Real.pi, angularKernel α A B θ| ≤
        C * B ^ (α / 2) * (L : ℝ) ^ (-1 - α)

/-- Finite group counting identity underlying the angular aliasing. -/
def GridMultiplicity : Prop :=
  ∀ q r : ℕ, 0 < q → 0 < r → ∀ f : ℝ → ℝ,
    Function.Periodic f (2 * Real.pi) → ∀ φ : ℝ,
      (∑ i : Fin q, ∑ j : Fin r,
        f (φ + 2 * Real.pi * ((i.val : ℝ) / q - (j.val : ℝ) / r))) =
      (Nat.gcd q r : ℝ) * ∑ k : Fin (Nat.lcm q r),
        f (φ + 2 * Real.pi * (k.val : ℝ) / Nat.lcm q r)

end BEMOC.Definitive
/- End BEMOCFormalization.Trapezoid -/

/- Begin BEMOCFormalization.Longitude -/

open scoped BigOperators
namespace BEMOC.Definitive

/-- The arithmetic double sum after reducing angular quadrature to gcd/lcm. -/
noncomputable def gcdSum (α : ℝ) (T : ℕ) : ℝ :=
  ∑ u ∈ Finset.Icc 1 T, ∑ v ∈ Finset.Icc 1 T,
    (Nat.gcd u v : ℝ) ^ (1 + α) / ((u : ℝ) * v) ^ (α / 2)

/-- The two zeta sums are finite because α>0. -/
def GcdSumBound (α : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ T : ℕ, gcdSum α T ≤ C * (T : ℝ) ^ 2

/-- Phase-uniform longitude estimate for the actual Diamond energy. -/
def LongitudeBound (α : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ N : ℕ, 4 ≤ N → ∀ φ : Phases N,
    |longitudeError α N φ| ≤ C * scale α N

end BEMOC.Definitive
/- End BEMOCFormalization.Longitude -/

/- Begin BEMOCFormalization.MainTheorem -/

namespace BEMOC.Definitive

/-- Main theorem target, with constants uniform over every N and every choice of phases. -/
def MainTheorem (α : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ N : ℕ, 4 ≤ N → ∀ φ : Phases N,
    0 ≤ deficit α N φ ∧ deficit α N φ ≤ C * scale α N

/-- Proved assembly; analytic estimates and geometric nonnegativity remain explicit inputs. -/
theorem main_theorem_of_estimates {α : ℝ}
    (hlat : LatitudeBound α) (hlong : LongitudeBound α)
    (hsmall : SmallSizeBound α) (hnonneg : DiamondNonnegative α) : MainTheorem α := by
  obtain ⟨A, hA, hlat⟩ := hlat
  obtain ⟨B, hB, hlong⟩ := hlong
  obtain ⟨S, hS, hsmall⟩ := hsmall
  refine ⟨A + B + S, by positivity, ?_⟩
  intro N hN φ
  refine ⟨hnonneg N hN φ, ?_⟩
  have hscale : 0 ≤ scale α N := Real.rpow_nonneg (Nat.cast_nonneg N) _
  by_cases hlarge : 1024 ≤ N
  · have ha := (le_abs_self (latitudeError α N)).trans (hlat N hlarge)
    have hb := (le_abs_self (longitudeError α N φ)).trans (hlong N hN φ)
    rw [deficit_eq_latitude_add_longitude]
    nlinarith [mul_nonneg (le_of_lt hS) hscale]
  · have hs := hsmall N hN (by omega) φ
    nlinarith [mul_nonneg (le_of_lt hA) hscale, mul_nonneg (le_of_lt hB) hscale]

/-- Complete unconditional statement to be proved; no proof of this target is asserted. -/
def MainTheoremTarget : Prop := ∀ α : ℝ, 0 < α → α < 2 → MainTheorem α

end BEMOC.Definitive
/- End BEMOCFormalization.MainTheorem -/

/- Begin BEMOCFormalization.CapDiscrepancy -/

open scoped BigOperators
open MeasureTheory
namespace BEMOC.Definitive

/-- Closed spherical cap, using the manuscript's chordal inner-product convention. -/
def cap (u : Sphere) (t : ℝ) : Set Sphere :=
  {x | t ≤ @Inner.inner ℝ Ambient _ (u : Ambient) (x : Ambient)}
/-- Empirical cap proportion minus normalized surface area. -/
noncomputable def capError {ι : Type} [Fintype ι] (X : ι → Sphere)
    (u : Sphere) (t : ℝ) : ℝ := by
  classical
  exact (∑ i, if X i ∈ cap u t then (1 : ℝ) else 0) / Fintype.card ι -
    (sigma (cap u t)).toReal
/-- Actual integrated squared cap error; the height measure is dt, of total mass two. -/
noncomputable def capDiscrepancySq {ι : Type} [Fintype ι] (X : ι → Sphere) : ℝ :=
  ∫ t in Set.Icc (-1 : ℝ) 1, ∫ u, capError X u t ^ 2 ∂sigma
/-- Actual L² spherical cap discrepancy, defined independently of energy. -/
noncomputable def capDiscrepancy {ι : Type} [Fintype ι] (X : ι → Sphere) : ℝ :=
  Real.sqrt (capDiscrepancySq X)

/-- Stolarsky with ordinary dt; replacing dt by dt/2 would change the factor to eight. -/
def StolarskyIdentity : Prop :=
  ∀ n : ℕ, 0 < n → ∀ X : Fin n → Sphere,
    4 * capDiscrepancySq X = continuousEnergy 1 - energy X 1 / (n : ℝ) ^ 2

/-- Geometric nonnegativity before invoking the invariance principle. -/
theorem capDiscrepancySq_nonneg {ι : Type} [Fintype ι] (X : ι → Sphere) :
    0 ≤ capDiscrepancySq X := by
  unfold capDiscrepancySq
  exact integral_nonneg (fun _ => integral_nonneg (fun _ => sq_nonneg _))

/-- Relabeling/cardinality bridge for the concrete point-index type. -/
def DiamondStolarsky : Prop :=
  ∀ N : ℕ, 4 ≤ N → ∀ φ : Phases N,
    4 * (N : ℝ) ^ 2 * capDiscrepancySq (point N φ) = deficit 1 N φ

/-- Beck's external lower estimate for actual sets, with injectivity explicit. -/
def BeckLowerBound : Prop :=
  ∃ c : ℝ, 0 < c ∧ ∀ n : ℕ, 1 ≤ n → ∀ X : Fin n → Sphere,
    Function.Injective X → c * (n : ℝ) ^ (-(3 : ℝ) / 4) ≤ capDiscrepancy X

/-- Corollary main, stronger by its uniformity in arbitrary ring phases. -/
def CapDiscrepancyCorollary : Prop :=
  ∃ c C : ℝ, 0 < c ∧ 0 < C ∧ ∀ N : ℕ, 4 ≤ N → ∀ φ : Phases N,
    c * (N : ℝ) ^ (-(3 : ℝ) / 4) ≤ capDiscrepancy (point N φ) ∧
    capDiscrepancy (point N φ) ≤ C * (N : ℝ) ^ (-(3 : ℝ) / 4)

end BEMOC.Definitive
/- End BEMOCFormalization.CapDiscrepancy -/

/- Begin BEMOCFormalization.Sobolev -/

open scoped BigOperators
open MeasureTheory
namespace BEMOC.Definitive

/-- Algebraic Euclidean Laplacian of a polynomial in three variables. -/
noncomputable def polynomialLaplacian (p : MvPolynomial (Fin 3) ℝ) : MvPolynomial (Fin 3) ℝ :=
  ∑ i : Fin 3, MvPolynomial.pderiv i (MvPolynomial.pderiv i p)
/-- Restriction of a homogeneous harmonic polynomial, defining degree-ℓ spherical harmonics. -/
def IsSphericalHarmonic (ℓ : ℕ) (Y : C(Sphere, ℝ)) : Prop :=
  ∃ p : MvPolynomial (Fin 3) ℝ, p.IsHomogeneous ℓ ∧ polynomialLaplacian p = 0 ∧
    ∀ x : Sphere, Y x = MvPolynomial.eval (fun i => (x : Ambient) i) p

/-- A complete real orthonormal harmonic system. Existence remains an explicit obligation. -/
structure HarmonicBasis where
  function : (ℓ : ℕ) → Fin (2 * ℓ + 1) → C(Sphere, ℝ)
  harmonic : ∀ ℓ k, IsSphericalHarmonic ℓ (function ℓ k)
  orthonormal : ∀ ℓ m k l,
    (∫ x, function ℓ k x * function m l x ∂sigma) =
      if ℓ = m ∧ k.val = l.val then 1 else 0
  complete : ∀ f : C(Sphere, ℝ),
    (∀ ℓ k, (∫ x, f x * function ℓ k x ∂sigma) = 0) → f = 0

/-- The actual Fourier coefficient of a continuous representative. -/
noncomputable def harmonicCoefficient (Y : HarmonicBasis) (f : C(Sphere, ℝ))
    (ℓ : ℕ) (k : Fin (2 * ℓ + 1)) : ℝ :=
  ∫ x, f x * Y.function ℓ k x ∂sigma
/-- Degree-ℓ contribution to the manuscript's specified spectral norm squared. -/
noncomputable def sobolevNormTerm (Y : HarmonicBasis) (s : ℝ)
    (f : C(Sphere, ℝ)) (ℓ : ℕ) : ℝ :=
  (1 + (ℓ : ℝ) * (ℓ + 1)) ^ s * ∑ k, harmonicCoefficient Y f ℓ k ^ 2
/-- Summability is essential: Lean's tsum of a divergent series cannot define this unit ball. -/
def SobolevUnitBall (Y : HarmonicBasis) (s : ℝ) (f : C(Sphere, ℝ)) : Prop :=
  Summable (sobolevNormTerm Y s f) ∧ (∑' ℓ, sobolevNormTerm Y s f ℓ) ≤ 1

/-- Integration error on continuous representatives, independently defined from energy. -/
noncomputable def quadratureError {ι : Type} [Fintype ι]
    (X : ι → Sphere) (f : C(Sphere, ℝ)) : ℝ :=
  (∑ i, f (X i)) / Fintype.card ι - ∫ x, f x ∂sigma
/-- Real worst-case error; boundedness is an explicit analytic obligation below. -/
noncomputable def sobolevWCE {ι : Type} [Fintype ι]
    (Y : HarmonicBasis) (s : ℝ) (X : ι → Sphere) : ℝ :=
  sSup {e : ℝ | ∃ f : C(Sphere, ℝ), SobolevUnitBall Y s f ∧ e = |quadratureError X f|}

/-- Evaluation boundedness needed before taking this supremum. -/
def SobolevEmbedding (Y : HarmonicBasis) (s : ℝ) : Prop :=
  ∃ K : ℝ, 0 < K ∧ ∀ f : C(Sphere, ℝ), SobolevUnitBall Y s f → ∀ x : Sphere, |f x| ≤ K

/-- Comparison for the specified spectral norm, not a renamed distance-kernel norm. -/
def SobolevEnergyComparison (Y : HarmonicBasis) (s : ℝ) : Prop :=
  ∃ A : ℝ, 0 < A ∧ ∀ n : ℕ, 0 < n → ∀ X : Fin n → Sphere,
    sobolevWCE Y s X ^ 2 ≤
      A * (continuousEnergy (2 * s - 2) - energy X (2 * s - 2) / (n : ℝ) ^ 2)

/-- Corollary wce, with an actual spectral unit ball and arbitrary ring phases. -/
def SobolevCorollary (Y : HarmonicBasis) (s : ℝ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ N : ℕ, 4 ≤ N → ∀ φ : Phases N,
    sobolevWCE Y s (point N φ) ≤ C * (N : ℝ) ^ (-s / 2)

/-- Separate lower estimate for the manuscript's accompanying optimality assertion. -/
def SobolevOptimality (Y : HarmonicBasis) (s : ℝ) : Prop :=
  ∃ c : ℝ, 0 < c ∧ ∀ n : ℕ, 1 ≤ n → ∀ X : Fin n → Sphere,
    Function.Injective X → c * (n : ℝ) ^ (-s / 2) ≤ sobolevWCE Y s X

end BEMOC.Definitive
/- End BEMOCFormalization.Sobolev -/

/- Begin BEMOCFormalization.Corollaries -/

namespace BEMOC.Definitive

/-- The Riesz exponent for the Sobolev corollary lies in the main theorem's open range. -/
theorem sobolev_exponent_range {s : ℝ} (hs1 : 1 < s) (hs2 : s < 2) :
    0 < 2 * s - 2 ∧ 2 * s - 2 < 2 := by constructor <;> linarith

/-- Dividing the energy scale by N² gives the squared Sobolev error exponent. -/
theorem sobolev_normalized_exponent (s : ℝ) :
    (1 - (2 * s - 2) / 2) - 2 = -s := by ring

/-- Dividing by N² and then taking a square root gives the cap discrepancy exponent. -/
theorem cap_normalized_exponent : ((1 : ℝ) - 1 / 2 - 2) / 2 = -3 / 4 := by norm_num

/-- Explicit corollary assembly obligation, including distinctness and the geometric bridge. -/
def CapAssembly : Prop :=
  ConstructionFacts → MainTheorem 1 → DiamondStolarsky → BeckLowerBound →
    CapDiscrepancyCorollary

/-- Explicit Sobolev assembly obligation; supremum boundedness is not implicit. -/
def SobolevAssembly : Prop :=
  ∀ Y : HarmonicBasis, ∀ s : ℝ, 1 < s → s < 2 → ConstructionFacts →
    MainTheorem (2 * s - 2) → SobolevEmbedding Y s →
    SobolevEnergyComparison Y s → SobolevCorollary Y s

/-- Full requested scaffold destination, including existence of the harmonic model. -/
def DefinitiveTargets : Prop :=
  MainTheoremTarget ∧ CapDiscrepancyCorollary ∧ Nonempty HarmonicBasis ∧
    ∀ Y : HarmonicBasis, ∀ s : ℝ, 1 < s → s < 2 →
      SobolevCorollary Y s ∧ SobolevOptimality Y s

end BEMOC.Definitive
/- End BEMOCFormalization.Corollaries -/

/- Begin BEMOCFormalization -/

/-!
# Deterministic Diamond points: definitive.tex scaffold

Every new module is imported transitively here. `BEMOC.Definitive.DefinitiveTargets`
is a proposition describing the requested destination, not a proved theorem.
The concrete definitions and theorems with proof bodies are checked by Lean.
See LEAN_FORMALIZATION.md and blueprint/README.md for the exact proof boundary.
-/
/- End BEMOCFormalization -/
